### ISSUE TITLE
Transport Endpoint is Not Connected

### ISSUE THREAD

**Issue by EyuphanMandiraci** [niveshbirangal/discord-rpc#17]
Traceback (most recent call last):
  File "/home/thekralgame/PycharmProjects/TheModpackDatabase/threads/discord_rpc_thread.py", line 15, in run
    rpc_obj = rpc.DiscordIpcClient.for_platform(client_id)
  File "/home/thekralgame/PycharmProjects/TheModpackDatabase/rpc.py", line 44, in for_platform
    return UnixDiscordIpcClient(client_id)
  File "/home/thekralgame/PycharmProjects/TheModpackDatabase/rpc.py", line 36, in __init__
    self._do_handshake()
  File "/home/thekralgame/PycharmProjects/TheModpackDatabase/rpc.py", line 51, in _do_handshake
    ret_op, ret_data = self.send_recv({'v': 1, 'client_id': self.client_id}, op=OP_HANDSHAKE)
  File "/home/thekralgame/PycharmProjects/TheModpackDatabase/rpc.py", line 99, in send_recv
    self.send(data, op)
  File "/home/thekralgame/PycharmProjects/TheModpackDatabase/rpc.py", line 107, in send
    self._write(header)
  File "/home/thekralgame/PycharmProjects/TheModpackDatabase/rpc.py", line 191, in _write
    self._sock.sendall(data)
OSError: [Errno 107] Transport endpoint is not connected

i get this error with example.py.
Discord Client is open.
I write application id in general information to client_id

**Comment by niveshbirangal** [comment]
reinstall discord from the official website. don't use snap or development version
