### ISSUE TITLE
Rpc connect issue

### ISSUE THREAD

**Issue by shasankp000** [niveshbirangal/discord-rpc#18]
Hi i followed the readme.md and on running a (modified version) of example.py 

`import rpc
import time
from time import mktime 

client_id = ''  # Your application's client ID as a string. # I didn't include my client id in the issue
rpc_obj = rpc.DiscordIpcClient.for_platform(client_id)  # Send the client ID to the rpc module
print("RPC connection successful.")

def rpc_connect():

    time.sleep(5)
    start_time = mktime(time.localtime())
    while True:
        activity = {
                "state": "Minecraft",  # anything you like
                "details": "Playing",  # anything you like
                "timestamps": {
                    "start": start_time
                },
                "assets": {
                    #"small_text": "",  # anything you like
                    #"small_image": "",  # must match the image key
                    "large_text": "Pycraft Launcher",  # anything you like
                    "large_image": "minecraft"  # must match the image key
                }
            }
        rpc_obj.set_activity(activity)
rpc_connect()`

I get this error: 

RPC connection successful.
Traceback (most recent call last):
  File "rpc_connect.py", line 30, in <module>
    rpc_connect()
  File "rpc_connect.py", line 28, in rpc_connect
    rpc_obj.set_activity(activity)
  File "/home/anonymous/Desktop/python_programs/python_minecraft/pycraft/rpc.py", line 137, in set_activity
    self.send(data)
  File "/home/anonymous/Desktop/python_programs/python_minecraft/pycraft/rpc.py", line 116, in send
    self._write(data_bytes)
  File "/home/anonymous/Desktop/python_programs/python_minecraft/pycraft/rpc.py", line 200, in _write
    self._sock.sendall(data)
ConnectionResetError: [Errno 104] Connection reset by peer

However i can still my program in the status.

![image](https://user-images.githubusercontent.com/46317225/132097152-d0f76398-f15c-41da-a7bd-5c2a8b27cf31.png)

What is happening here exactly?

(sorry for poor editing of comment :sweat_smile: )

**Comment by shasankp000** [comment]
Ah well nvm i fixed the issue. Im closing it.
