### ISSUE TITLE
Socket is not connected

### ISSUE THREAD

**Issue by rzubrycki** [niveshbirangal/discord-rpc#2]
Hi I tried your tutorial, but i got this error in the console after "python3 example.py"

Demo for python-discord-rpc
failed to open '/var/folders/_6/gbxvg51d3wg13b34lkc7cqwr0000gn/T/discord-ipc-0': [Errno 61] Connection refused
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    rpc_obj = rpc.DiscordIpcClient.for_platform(client_id)
  File "/Users/robertzubrycki/Work/learning/discord-rpc/rpc.py", line 53, in for_platform
    return UnixDiscordIpcClient(client_id)
  File "/Users/robertzubrycki/Work/learning/discord-rpc/rpc.py", line 45, in __init__
    self._do_handshake()
  File "/Users/robertzubrycki/Work/learning/discord-rpc/rpc.py", line 60, in _do_handshake
    ret_op, ret_data = self.send_recv({'v': 1, 'client_id': self.client_id}, op=OP_HANDSHAKE)
  File "/Users/robertzubrycki/Work/learning/discord-rpc/rpc.py", line 108, in send_recv
    self.send(data, op)
  File "/Users/robertzubrycki/Work/learning/discord-rpc/rpc.py", line 116, in send
    self._write(header)
  File "/Users/robertzubrycki/Work/learning/discord-rpc/rpc.py", line 201, in _write
    self._sock.sendall(data)
OSError: [Errno 57] Socket is not connected

**Comment by niveshbirangal** [comment]
yea, this method does not work. I have to code it again, but currently, I don't have the bandwidth.

**Comment by niveshbirangal** [comment]
Hey, Make sure you are using discord desktop application, and it should be running.
