### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by VladatBoss** [niveshbirangal/discord-rpc#20]
While I was using this I got these errors:

Demo for python-discord-rpc Adobe illustrator
Traceback (most recent call last):
  File "example.py", line 7, in <module>
    rpc_obj = rpc.DiscordIpcClient.for_platform(client_id)  # Send the client ID to the rpc module
  File "/home/runner/discord-rpc/rpc.py", line 52, in for_platform
    return UnixDiscordIpcClient(client_id)
  File "/home/runner/discord-rpc/rpc.py", line 44, in __init__
    self._do_handshake()
  File "/home/runner/discord-rpc/rpc.py", line 59, in _do_handshake
    ret_op, ret_data = self.send_recv({'v': 1, 'client_id': self.client_id}, op=OP_HANDSHAKE)
  File "/home/runner/discord-rpc/rpc.py", line 107, in send_recv
    self.send(data, op)
  File "/home/runner/discord-rpc/rpc.py", line 115, in send
    self._write(header)
File "/home/runner/discord-rpc/rpc.py", line 200, in _write
    self._sock.sendall(data)
OSError: [Errno 107] Transport endpoint is not connected

I feel like I made a stupid mistake while reading it I'll try to fix it.

**Comment by VladatBoss** [comment]
I ran this on Replit btw.

**Comment by niveshbirangal** [comment]
Don't use online IDE

**Comment by f1bdis** [comment]
Hey, Thanks this was the same error. I used on a terminal works fine.
