### ISSUE TITLE
Trying to use on linux

### ISSUE THREAD

**Issue by Bugleman** [niveshbirangal/discord-rpc#21]
OSError: [Errno 107] Transport endpoint is not connected

feull trace
```
usr/bin/python3 /home/pi/Downloads/discord-rpc/example.py
Demo for python-discord-rpc Adobe illustrator
Traceback (most recent call last):
  File "/home/pi/Downloads/discord-rpc/example.py", line 7, in <module>
    rpc_obj = rpc.DiscordIpcClient.for_platform(client_id)  # Send the client ID to the rpc module
  File "/home/pi/Downloads/discord-rpc/rpc.py", line 52, in for_platform
    return UnixDiscordIpcClient(client_id)
  File "/home/pi/Downloads/discord-rpc/rpc.py", line 44, in __init__
    self._do_handshake()
  File "/home/pi/Downloads/discord-rpc/rpc.py", line 59, in _do_handshake
    ret_op, ret_data = self.send_recv({'v': 1, 'client_id': self.client_id}, op=OP_HANDSHAKE)
  File "/home/pi/Downloads/discord-rpc/rpc.py", line 107, in send_recv
    self.send(data, op)
  File "/home/pi/Downloads/discord-rpc/rpc.py", line 115, in send
    self._write(header)
  File "/home/pi/Downloads/discord-rpc/rpc.py", line 200, in _write
    self._sock.sendall(data)
OSError: [Errno 107] Transport endpoint is not connected
```

**Comment by niveshbirangal** [comment]
The issue has been already discussed in a previously closed one. Please check it out.
