### ISSUE TITLE
Error when trying to edit activity

### ISSUE THREAD

**Issue by Impre-visible** [niveshbirangal/discord-rpc#25]
I can edit the actual activity easily, but my script seems to create problems, I got this error

```
Traceback (most recent call last):
  File "C:\Users\imprv\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\imprv\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\imprv\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\imprv\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\imprv\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "g:\Projets\Chocolate\app.py", line 1216, in sendDiscordPresence
    rpc_obj.set_activity(activity)
  File "g:\Projets\Chocolate\rpc.py", line 137, in set_activity
    self.send(data)
  File "g:\Projets\Chocolate\rpc.py", line 115, in send
    self._write(header)
  File "g:\Projets\Chocolate\rpc.py", line 160, in _write
    self._f.flush()
OSError: [Errno 22] Invalid argument
```
here's the script

```py
@app.route("/sendDiscordPresence/<name>/<actualDuration>/<totalDuration>")
def sendDiscordPresence(name, actualDuration, totalDuration):
    actualDuration = actualDuration
    totalDuration = totalDuration
    rpc_obj = rpc.DiscordIpcClient.for_platform(client_id)
    activity = {
        "state": "Chocolate",  # anything you like
        "details": f"Watching {name} | {actualDuration}/{totalDuration}",  # anything you like
        "assets": {
            "small_text": "Chocolate",  # anything you like
            "small_image": "None",  # must match the image key
            "large_text": "Chocolate",  # anything you like
            "large_image": "largeimage"  # must match the image key
        }
    }
    print(json.dumps(activity, indent=4))
    rpc_obj.set_activity(activity)
    return json.dumps(f"You sent richPresence Data with this informations : name:{name}, actualDuration:{actualDuration}, totalDuration:{totalDuration}")```

**Comment by Impre-visible** [comment]
I patched the error with a global
