### ISSUE TITLE
OSError: [Errno 107] Transport endpoint is not connected.

### ISSUE THREAD

**Issue by MrMarvell0us** [niveshbirangal/discord-rpc#3]
After run this:
`marvellous@Marvellous-ROG:~/Documents/discord-rpc-master$ python3 example.py `

```
Demo for python-discord-rpc
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    rpc_obj = rpc.DiscordIpcClient.for_platform(client_id) #Send the client ID to the rpc module
  File "/home/marvellous/Documents/discord-rpc-master/rpc.py", line 53, in for_platform
    return UnixDiscordIpcClient(client_id)
  File "/home/marvellous/Documents/discord-rpc-master/rpc.py", line 45, in __init__
    self._do_handshake()
  File "/home/marvellous/Documents/discord-rpc-master/rpc.py", line 60, in _do_handshake
    ret_op, ret_data = self.send_recv({'v': 1, 'client_id': self.client_id}, op=OP_HANDSHAKE)
  File "/home/marvellous/Documents/discord-rpc-master/rpc.py", line 108, in send_recv
    self.send(data, op)
  File "/home/marvellous/Documents/discord-rpc-master/rpc.py", line 116, in send
    self._write(header)
  File "/home/marvellous/Documents/discord-rpc-master/rpc.py", line 201, in _write
    self._sock.sendall(data)
OSError: [Errno 107] Transport endpoint is not connected
```

**Comment by niveshbirangal** [comment]
make sure you are using correct client id

**Comment by niveshbirangal** [comment]
Also, do make sure you have discord desktop client opened. if not it will give this error

**Comment by thalibarrifqi** [comment]
Hello @niveshbirangal ,
I followed your tutorial and use the code provided by you. I have discord installed on my system. When I run this code directly from terminal, I got no error and discord rich presence working well, but when I run my code as service on linux ubuntu. I got this error.
Do you have any idea why this is happen?
Thank you

**Comment by niveshbirangal** [comment]
@thalibarrifqi It's because you have installed it through snap as sandboxing changes the file path and it may not simulate the actual network environments if you are using it for that purpose.
