### ISSUE TITLE
discordrpc.exceptions.Error: Failed to open '\\\\?\\pipe\\discord-ipc-0': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-0'

### ISSUE THREAD

**Issue by syradeveloper** [niveshbirangal/discord-rpc#30]
Traceback (most recent call last):
  File "D:\git\ply_alib\data\libraries\Inters.py", line 54, in <module>
    rpc_connect()
  File "D:\git\ply_alib\data\libraries\Inters.py", line 39, in rpc_connect
    rpc = discordrpc.RPC(app_id=herewasmyapp_id, output=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SystemX\AppData\Local\Programs\Python\Python312\Lib\site-packages\discordrpc\presence.py", line 41, in __init__
    self.ipc = WindowsPipe(app_id)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SystemX\AppData\Local\Programs\Python\Python312\Lib\site-packages\discordrpc\presence.py", line 137, in __init__
    raise Error("Failed to open {!r}: {}".format(path, e))
discordrpc.exceptions.Error: Failed to open '\\\\?\\pipe\\discord-ipc-0': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-0'

**Comment by niveshbirangal** [comment]
I think you are running the wrong file, you have to run example.py
